development:
  adapter: mysql2
  encoding: utf8
  database: mongoid_user_development
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: mongoid_user_test
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: mongoid_user_demo
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true